export const SHIPMENT_TRACKING_STEPS = [
  { id: 'ship_request', title: 'Ship Requested', description: 'Ship request from {userName}' },
  { id: 'payment_pending', title: 'Payment Pending', description: 'Payment Pending for {userName}', defaultDescription: 'Invoice sent and waiting for freight payment' },
  { id: 'payment_approval_pending', title: 'Payment Approval Pending', description: 'Payment Approval Pending by {userName}', defaultDescription: 'Waiting for payment approval' },
  { id: 'payment_approved', title: 'Payment Approved', description: 'Payment Approved by {userName}', defaultDescription: 'Freight invoice payment settled' },
  { id: 'ready_to_ship', title: 'Ready To Ship', description: 'Label Generated by {userName}', defaultDescription: 'Ready To Ship' },
  { id: 'departed', title: 'Departed from Origin', description: 'Label Generated by {userName}', defaultDescription: 'No tracking Url.' },
];

export const SHIPMENT_STATUS_TO_STEP_ID_MAPPING: Record<string, string> = {
  ship_request: 'ship_request',
  payment_pending: 'payment_pending',
  payment_approval_pending: 'payment_approval_pending',
  payment_approved: 'payment_approved',
  ready_to_ship: 'ready_to_ship',
  departed: 'departed'
};

export const SHOPPING_TRACKING_STEPS = [
  { id: 'REQUESTED', title: 'Requested', description: 'Requested by {userName}' },
  { id: 'QUOTED', title: 'Quotation Ready', description: 'Quoted for {userName}', defaultDescription: 'Quotation is not ready yet!' },
  { id: 'QUOTATION_CONFIRMED', title: 'Quotation Confirmed', description: 'Quotation Confirmed by {userName}', defaultDescription: 'Quotation is not confirmed yet!' },
  { id: 'INVOICED', title: 'Invoiced', description: 'Invoice raised by {userName}', defaultDescription: 'Waiting for raise invoice' },
  { id: 'PAYMENT_PENDING', title: 'Pending Payment Approval', description: 'Payment slip uploaded by {userName}', defaultDescription: 'Waiting for upload payment slip' },
  { id: 'PAYMENT_APPROVED', title: 'Payment Approved', description: 'Payment Approved by {userName}', defaultDescription: 'Waiting for payment approval' },
  { id: 'ORDER_PLACED', title: 'Order placed', description: 'Order Placed by {userName}', defaultDescription: 'Waiting for complete' },
];

export const SHOPPING_STATUS_TO_STEP_ID_MAPPING: Record<string, string> = {
  REQUESTED: 'REQUESTED',
  QUOTATION_READY: 'QUOTED',
  QUOTATION_CONFIRMED: 'QUOTATION_CONFIRMED',
  INVOICED: 'INVOICED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  ORDER_PLACED: 'ORDER_PLACED',
};

export const PICKUP_TRACKING_STEPS = [
  { id: 'REQUESTED', title: 'Requested', description: 'Requested by {userName}' },
  { id: 'QUOTED', title: 'Quotation Ready', description: 'Quoted for {userName}', defaultDescription: 'Quotation is not ready yet!' },
  { id: 'CONFIRMED', title: 'Confirmed', description: 'Confirmed by {userName}', defaultDescription: 'Waiting for confirmation!' },
  { id: 'PICKED', title: 'Picked', description: 'Picked by {userName}', defaultDescription: 'Waiting for complete' },
];

export const PICKUP_STATUS_TO_STEP_ID_MAPPING: Record<string, string> = {
  REQUESTED: 'REQUESTED',
  QUOTED: 'QUOTED',
  CONFIRMED: 'CONFIRMED',
  PICKED: 'PICKED',
};