import React, { useEffect, useState } from 'react';
import { Box, CircularProgress, Grid } from '@mui/material';
import { useParams } from 'react-router-dom';

import TopNavbar from '../components/Layout/TopNavbar.tsx';
import { getShipmentsByShipmentNo } from '../services/api.services.ts';
import ShipmentDetailsSection from '../components/Shipments/Detail/ShipmentDetailsSection.tsx';
import PackagesSection from '../components/Shipments/Detail/PackagesSection.tsx';
import ShipmentsPhotosSection from '../components/Shipments/Detail/ShipmentsPhotosSection.tsx';
import ShippingAddress from '../components/Shipments/Detail/ShippingAddress.tsx';
import TrackingStatus from '../components/common/Tracking/TrackingStatus.tsx';
import { formatDateTime } from '../utils/formatDateTime.ts';
import ActionLogs from '../components/Shipments/Detail/ActionLogs.tsx';
import ShipmentHeader from '../components/Shipments/Detail/ShipmentHeader.tsx';

const ShipmentDetail: React.FC = () => {
  const { shipment_no } = useParams();
  const [shipments, setShipments] = useState<any | null>(null);
  const [loading, setLoading] = useState(true);

  const fetchShipments = async () => {
    if (!shipment_no) return;
    setLoading(true);
    try {
      const data = await getShipmentsByShipmentNo(shipment_no);
      setShipments(data);
    } catch (err) {
      console.error("Error fetching shopping request:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchShipments();
  }, [shipment_no]);

  const SHIPMENT_TRACKING_STEPS = [
    { id: 'REQUEST_SHIP', title: 'Ship Requested', description: 'Ship request from {userName}' },
    { id: 'PAYMENT_PENDING', title: 'Payment Pending', description: 'Payment Pending for {userName}', defaultDescription: 'Invoice sent and waiting for freight payment' },
    { id: 'PAYMENT_APPROVAL_PENDING', title: 'Payment Approval Pending', description: 'Payment Approval Pending by {userName}', defaultDescription: 'Waiting for payment approval' },
    { id: 'PAYMENT_APPROVED', title: 'Payment Approved', description: 'Payment Approved by {userName}', defaultDescription: 'Freight invoice payment settled' },
    { id: 'READY_TO_SHIP', title: 'Readt To Ship', description: 'Label Generated by {userName}', defaultDescription: 'Ready To Ship' },
    { id: 'DEPARTED', title: 'Departed from Origin', description: 'Label Generated by {userName}', defaultDescription: 'No tracking Url.' },
  ];

  const STATUS_TO_STEP_ID_MAPPING: Record<string, string> = {
    REQUEST_SHIP: 'REQUEST_SHIP',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    PAYMENT_APPROVAL_PENDING: 'PAYMENT_APPROVAL_PENDING',
    PAYMENT_APPROVED: 'PAYMENT_APPROVED',
    LABEL_GENERATED: 'LABEL_GENERATED',
    READY_TO_SHIP: 'READY_TO_SHIP',
    DEPARTED: 'DEPARTED'
  };

  const prepareTrackingData = () => {
    const trackingHistory = shipments.tracking_requests || [];
    const isRejected = shipments.status.toUpperCase() === 'REJECTED';

    const statuses = SHIPMENT_TRACKING_STEPS.map(step => {
      let description = step.defaultDescription || '';
      let date: string | undefined = undefined;
      let isComplete = false;
      const userName = shipments.user?.name;

      const historyItem = trackingHistory.find( track => {
        const upperCaseStatus = track.status.toUpperCase();
        return STATUS_TO_STEP_ID_MAPPING[upperCaseStatus] === step.id || upperCaseStatus === step.id;
      });

      if (historyItem) {
        isComplete = true;
        date = historyItem.created_at;
      }
      
      if (isComplete) {
        description = step.description.replace('{userName}', userName);
      }

      return {
        id: step.id,
        title: step.title,
        description,
        date: formatDateTime(date),
      };
    });
    
    let currentStageId: string;
    const upperCaseStatus = shipments.status.toUpperCase();
    const mappedId = STATUS_TO_STEP_ID_MAPPING[upperCaseStatus];

    if (mappedId && !isRejected) {
      currentStageId = mappedId;
    } else {
      const lastCompletedStep = [...statuses].reverse().find(s => s.date && s.date.trim() !== '');
      currentStageId = lastCompletedStep ? (lastCompletedStep.id as string) : 'REQUEST_SHIP';
    }

    if (isRejected) {
      const currentStageIndex = statuses.findIndex(s => s.id === currentStageId);
      if (currentStageIndex > -1) {
        for (let i = currentStageIndex + 1; i < statuses.length; i++) {
          const originalStep = SHIPMENT_TRACKING_STEPS.find(s => s.id === statuses[i].id);

          statuses[i].date = formatDateTime(undefined);
          statuses[i].description = originalStep?.defaultDescription || '';
        }
      }
    }

    return { statuses, currentStageId };
  };
  
  if (loading || !shipments) {
    return (
      <Box sx={{ p: 1 }}>
        <TopNavbar />
        <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}>
          <CircularProgress />
        </Box>
      </Box>
    );
  }

  const { statuses, currentStageId } = prepareTrackingData();

  return (
    <Box sx={{ p: 1 }}>
      <TopNavbar
        pageTitle="Shipments"
        pageSubtitle={shipment_no}
      />

      <ShipmentHeader 
        shipments={shipments}
        onRefresh={fetchShipments}
      />

      <Grid container spacing={2}>
        <Grid size={{ xs: 12, md: 8 }}  sx={{ mt: 2 }}>
          <ShipmentDetailsSection 
            shipments={shipments}
            loading={loading}
            onRefresh={fetchShipments}
          />

          <PackagesSection
            packages={shipments?.packages} 
          />

          {/* {showInvoiceTable && (
            <InvoiceTable 
              id={packageData.id}
              invoice={getInvoice(packageData)}
              payment_slips={paymentSlips}
              status={packageData.status.value}
              isApprovingPayment={isApprovingPayment}
              onApprovePayment={handleApprovePayment}
              onStatusUpdated={async () => {
                const updated = await getPackageById(packageData.package_id);
                setPackageData(updated);
                await fetchPaymentSlips(updated.shipment_uuid);
              }}
            />
          )} */}           
        </Grid>

        <Grid size={{ xs: 12, md: 4 }}>
          <ShippingAddress
            shipments={shipments}
          />

          <ShipmentsPhotosSection 
            shipments={shipments}
            documents={[]}
            // onUploadSuccess={handleActionLogUpdate}
          />

          <TrackingStatus
            statuses={statuses}
            currentStageId={currentStageId}
          />

          <ActionLogs /> 
        </Grid>
      </Grid>
    </Box>
  );
};

export default ShipmentDetail;