import React, { useEffect, useState } from 'react';
import { Box, CircularProgress, Grid } from '@mui/material';
import { useParams } from 'react-router-dom';

import TopNavbar from '../components/Layout/TopNavbar.tsx';
import { getShipmentsByShipmentNo, updateShipmentStatus } from '../services/api.services.ts';
import ShipmentDetailsSection from '../components/Shipments/Detail/ShipmentDetailsSection.tsx';
import PackagesSection from '../components/Shipments/Detail/PackagesSection.tsx';
import ShipmentsPhotosSection from '../components/Shipments/Detail/ShipmentsPhotosSection.tsx';
import ShippingAddress from '../components/Shipments/Detail/ShippingAddress.tsx';
import TrackingStatus from '../components/common/Tracking/TrackingStatus.tsx';
import { formatDateTime } from '../utils/formatDateTime.ts';
import ActionLogs from '../components/Shipments/Detail/ActionLogs.tsx';
import ShipmentHeader from '../components/Shipments/Detail/ShipmentHeader.tsx';
import InvoiceTable from '../components/ShoppingRequests/Detail/InvoiceTable.tsx';
import { toast } from 'sonner';

const ShipmentDetail: React.FC = () => {
  const { shipment_no } = useParams();
  const [shipments, setShipments] = useState<any | null>(null);
  const [isApprovingPayment, setIsApprovingPayment] = useState(false);
  const [loading, setLoading] = useState(true);

  const fetchShipments = async () => {
    if (!shipment_no) return;
    setLoading(true);
    try {
      const data = await getShipmentsByShipmentNo(shipment_no);
      setShipments(data);
    } catch (err) {
      console.error("Error fetching shopping request:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchShipments();
  }, [shipment_no]);

  const handleApprovePayment = async (id: string) => {
    if (!id) return;
    setIsApprovingPayment(true);
    try {
      await updateShipmentStatus(id, "PAYMENT_APPROVED")
      await fetchShipments()
      toast.success('Payment approved successfully!');
    } catch (err) {
      console.error('Failed to approve payment:', err);
      toast.error('Failed to approve payment.');
    } finally {
      setIsApprovingPayment(false);
    }
  };

  const SHIPMENT_TRACKING_STEPS = [
    { id: 'ship_request', title: 'Ship Requested', description: 'Ship request from {userName}' },
    { id: 'payment_pending', title: 'Payment Pending', description: 'Payment Pending for {userName}', defaultDescription: 'Invoice sent and waiting for freight payment' },
    { id: 'payment_approval_pending', title: 'Payment Approval Pending', description: 'Payment Approval Pending by {userName}', defaultDescription: 'Waiting for payment approval' },
    { id: 'payment_approved', title: 'Payment Approved', description: 'Payment Approved by {userName}', defaultDescription: 'Freight invoice payment settled' },
    { id: 'ready_to_ship', title: 'Ready To Ship', description: 'Label Generated by {userName}', defaultDescription: 'Ready To Ship' },
    { id: 'departed', title: 'Departed from Origin', description: 'Label Generated by {userName}', defaultDescription: 'No tracking Url.' },
  ];

  const STATUS_TO_STEP_ID_MAPPING: Record<string, string> = {
    ship_request: 'ship_request',
    payment_pending: 'payment_pending',
    payment_approval_pending: 'payment_approval_pending',
    payment_approved: 'payment_approved',
    ready_to_ship: 'ready_to_ship',
    departed: 'departed'
  };

  const getInvoice = (shipments: any) => {
    const invoice = shipments.invoice;
    if (invoice > 0) {
      return invoice;
    } else {
      return {id: "temp", invoice_no: "-", amount: 0, total: 0, status: "UNPAID"};
    }
  };

  const prepareTrackingData = () => {
    const trackingHistory = shipments.tracking_requests || [];
    const isRejected = shipments.status.toUpperCase() === 'REJECTED';

    const statuses = SHIPMENT_TRACKING_STEPS.map(step => {
      let description = step.defaultDescription || '';
      let date: string | undefined = undefined;
      let isComplete = false;
      const userName = shipments.user?.name;

      const historyItem = trackingHistory.find( track => {
        return STATUS_TO_STEP_ID_MAPPING[track.status] === step.id;
      });

      if (historyItem) {
        isComplete = true;
        date = historyItem.created_at;
      }
      
      if (isComplete) {
        description = step.description.replace('{userName}', userName);
      }

      return {
        id: step.id,
        title: step.title,
        description,
        date: formatDateTime(date),
      };
    });
    
    let currentStageId: string;
    const upperCaseStatus = shipments.status.toUpperCase();
    const mappedId = STATUS_TO_STEP_ID_MAPPING[upperCaseStatus];

    if (mappedId && !isRejected) {
      currentStageId = mappedId;
    } else {
      const lastCompletedStep = [...statuses].reverse().find(s => s.date && s.date.trim() !== '');
      currentStageId = lastCompletedStep ? (lastCompletedStep.id as string) : 'REQUEST_SHIP';
    }

    if (isRejected) {
      const currentStageIndex = statuses.findIndex(s => s.id === currentStageId);
      if (currentStageIndex > -1) {
        for (let i = currentStageIndex + 1; i < statuses.length; i++) {
          const originalStep = SHIPMENT_TRACKING_STEPS.find(s => s.id === statuses[i].id);

          statuses[i].date = formatDateTime(undefined);
          statuses[i].description = originalStep?.defaultDescription || '';
        }
      }
    }

    return { statuses, currentStageId };
  };
  
  if (loading || !shipments) {
    return (
      <Box sx={{ p: 1 }}>
        <TopNavbar />
        <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}>
          <CircularProgress />
        </Box>
      </Box>
    );
  }

  const { statuses, currentStageId } = prepareTrackingData();
  const showInvoiceTable = ["PAYMENT_PENDING", "PAYMENT_APPROVAL_PENDING", "PAYMENT_APPROVED", "READY_TO_SHIP", "DEPARTED"]
    .includes(shipments.status);

  return (
    <Box sx={{ p: 1 }}>
      <TopNavbar
        pageTitle="Shipments"
        pageSubtitle={shipment_no}
      />

      <ShipmentHeader 
        shipments={shipments}
        onRefresh={fetchShipments}
      />

      <Grid container spacing={2}>
        <Grid size={{ xs: 12, md: 8 }}  sx={{ mt: 2 }}>
          <ShipmentDetailsSection 
            shipments={shipments}
            loading={loading}
            onRefresh={fetchShipments}
          />

          <PackagesSection
            packages={shipments?.packages} 
          />

          {showInvoiceTable && (
            <InvoiceTable
              invoice={getInvoice(shipments)}
              payment_slips={shipments.payment_slips}
              status={shipments.status}
              isApprovingPayment={isApprovingPayment}
              onApprovePayment={() => handleApprovePayment(shipments.id)} 
            />
          )}           
        </Grid>

        <Grid size={{ xs: 12, md: 4 }}>
          <ShippingAddress
            shipments={shipments}
          />

          <ShipmentsPhotosSection 
            shipments={shipments}
            documents={shipments.shipment_photos || []}
            onUploadSuccess={fetchShipments}
          />

          <TrackingStatus
            statuses={statuses}
            currentStageId={currentStageId}
          />

          <ActionLogs /> 
        </Grid>
      </Grid>
    </Box>
  );
};

export default ShipmentDetail;